set FOREIGN_KEY_CHECKS=0;

CREATE TABLE `ieclient_financial`
(
	`FINANCIAL_RECORD_ID` INTEGER NOT NULL AUTO_INCREMENT,
	`FUNCTION_CD` VARCHAR(3) 	 NULL,
	`COMPANY_CD` VARCHAR(4) 	 NULL,
	`GENERAL_RECORD_ID` INTEGER 	 NULL,
	CONSTRAINT `PK_CUST_FINANCIAL` PRIMARY KEY (`FINANCIAL_RECORD_ID` ASC)	
) ENGINE=InnoDB;

ALTER TABLE `ieclient_financial` 
 ADD INDEX `IXFK_CUST_FINANCIAL_CUST_GENERAL` (`GENERAL_RECORD_ID` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `ieclient_financial` 
 ADD CONSTRAINT `FK_CUST_FINANCIAL_CUST_GENERAL`
	FOREIGN KEY (`GENERAL_RECORD_ID`) REFERENCES `ieclient_general` (`GENERAL_RECORD_ID`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
